name: ファイルが適切に整形されているかの確認

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  test:
    name: ファイルが適切に整形されているかの確認
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # 後続の操作では認証情報を使用しないため、破棄するように設定
          persist-credentials: false

      - name: Node.js/npm のセットアップと依存関係のインストール
        uses: ./.github/actions/setup-npm

      - name: ファイルが適切に整形されているかの確認
        run: npm run format:check
