name: GitHub Actions ワークフローのチェック

on:
  push:
  workflow_dispatch:

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  zizmor:
    name: zizmor を用いてワークフローをチェック
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: read
      security-events: write

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # 後続の操作では認証情報を使用しないため、破棄するように設定
          persist-credentials: false

      - name: zizmor の実行
        uses: zizmorcore/zizmor-action@e639db99335bc9038abc0e066dfcd72e23d26fb4 # v0.3.0
        with:
          # 使用する zizmor 自体のバージョンを固定した方がいいのかどうかについては
          # https://github.com/zizmorcore/zizmor-action/issues/52 を参照。
          # 上記の issue の様子を見つつ、一旦 latest を指定しておくことにしておく。
          version: latest
