name: テストの実行

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  cnako:
    name: cnako ランタイム用のファイルのテストの実行
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # 後続の操作では認証情報を使用しないため、破棄するように設定
          persist-credentials: false

      - name: Node.js/npm のセットアップと依存関係のインストール
        uses: ./.github/actions/setup-npm

      - name: テストの実行
        run: npm run test:cnako

  wnako:
    name: wnako ランタイム用にバンドルされたファイルのテストの実行
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # 後続の操作では認証情報を使用しないため、破棄するように設定
          persist-credentials: false

      - name: Node.js/npm のセットアップと依存関係のインストール
        uses: ./.github/actions/setup-npm

      - name: Playwright が使用するテスト用のブラウザをインストール
        run: npx playwright install --with-deps

      - name: テストの実行
        run: npm run test:wnako
